### ISSUE TITLE
Scannermod stopped working with latest patch.

### ISSUE THREAD

**Issue by revdanielc** [nieboczek/gss-mod-manager#8]
I even reassigned the TAB key to O so it wouldn't interfere with employee stuff.  When I click a tag, it says it adds the item to the cart, but when I check the computer, nothing in the cart.

**Comment by nieboczek** [comment]
The v1.0 update broke ScannerMod, I'm looking to fix this. Please use NexusMods or the GSS Modding Community to report bugs for mods. This repository should contain only issues related to GSS Mod Manager.
